apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push-image
  namespace: narendra-namespace
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.repo-url) source
    - name: build-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: /workspace
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
      script: |
        #!/busybox/sh
        /kaniko/executor \
          --dockerfile=source/Dockerfile \
          --context=source/ \
          --destination=$(params.image-url)