apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: el-github-listener-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: github-webhook.yourdomain.com  # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: el-github-listener
                port:
                  number: 8080  # Must match your EventListener service port
