apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: narendra-namespace
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  tasks:
    - name: build-push-task
      taskRef:
        name: build-push-image
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: image-url
          value: $(params.image-url)
