apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-push-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: image-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: build-push-run-
      spec:
        taskRef:
          name: build-push-task  # Make sure this is your Tekton Task name
        params:
          - name: gitrevision
            value: $(tt.params.gitrevision)
          - name: gitrepositoryurl
            value: $(tt.params.gitrepositoryurl)
          - name: image-url
            value: $(tt.params.image-url)
        workspaces:
          - name: source
            emptyDir: {}
        serviceAccountName: pipeline-sa  # Make sure this SA exists