kind: Service
apiVersion: v1
metadata:
  name: barista
spec:
  selector:
    app: barista
  ports:
  - port: 8080
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: barista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista
  template:
    metadata:
      labels:
        app: barista
    spec:
      containers:
      - name: barista
        image: sdaschner/barista:quarkus-testing-2
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /q/health
            port: 8080
      restartPolicy: Always
---