kind: Service
apiVersion: v1
metadata:
  name: coffee-shop
spec:
  selector:
    app: coffee-shop
  ports:
  - port: 8080
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: coffee-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-shop
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:quarkus-testing-2
        imagePullPolicy: Always
#        env:
#          - name: QUARKUS_DATASOURCE_JDBC_URL
#            value: 'jdbc:postgresql://cluster:5432/postgres'
#          - name: QUARKUS_DATASOURCE_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                key: superuser-password
#                name: cluster
        readinessProbe:
          httpGet:
            path: /q/health
            port: 8080
      restartPolicy: Always
---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: coffee-shop
spec:
  defaultBackend:
    service:
      name: coffee-shop
      port:
        number: 8080
---