apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: coffee-shop-db
spec:
  instances: 1
  postgres:
    version: '15.0'
  pods:
    persistentVolume:
      size: '5Gi'
  managedSql:
    scripts:
    - sgScript: coffee-shop-script
  prometheusAutobind: true
---
