apiVersion: stackgres.io/v1
kind: SGScript
metadata:
  name: coffee-shop-script
spec:
  scripts:
  - name: clear-db
    script: |
     DROP DATABASE IF EXISTS coffeeshopdb;
  - name: create-user
    scriptFrom:
      secretKeyRef:
        name: coffee-shop-db-user
        key: sql
  - name: create-database
    script: |
      CREATE DATABASE coffeeshopdb owner coffeeshop encoding 'UTF8' locale 'en_US.UTF-8' template template0;
  - name: schema-init-data
    script: |
      CREATE TABLE orders (
                                     id uuid NOT NULL,
                                     status character varying(255) NOT NULL,
                                     type character varying(255) NOT NULL,
                                     origin_name character varying(255) NOT NULL
      );
      
      CREATE TABLE origin_coffee_types (
                                                  origin_name character varying(255) NOT NULL,
                                                  coffee_type character varying(255) NOT NULL
      );
      
      CREATE TABLE origins (
          name character varying(255) NOT NULL
      );
      
      ALTER TABLE ONLY orders
          ADD CONSTRAINT orders_pkey PRIMARY KEY (id);
      
      ALTER TABLE ONLY origin_coffee_types
          ADD CONSTRAINT origin_coffee_types_pkey PRIMARY KEY (origin_name, coffee_type);
      
      ALTER TABLE ONLY origins
          ADD CONSTRAINT origins_pkey PRIMARY KEY (name);
      
      ALTER TABLE ONLY origin_coffee_types
          ADD CONSTRAINT fksny5vf8j30otg213opmbp0ab9 FOREIGN KEY (origin_name) REFERENCES origins(name);
      
      ALTER TABLE ONLY orders
          ADD CONSTRAINT fkt474abpx5pxojjm61tb1d64vp FOREIGN KEY (origin_name) REFERENCES origins(name);
      
      ALTER TABLE orders OWNER TO coffeeshop;
      ALTER TABLE origins OWNER TO coffeeshop;
      ALTER TABLE origin_coffee_types OWNER TO coffeeshop;
      
      --
      
      INSERT INTO origins VALUES ('Ethiopia');
      INSERT INTO origin_coffee_types VALUES ('Ethiopia', 'ESPRESSO');
      INSERT INTO origin_coffee_types VALUES ('Ethiopia', 'LATTE');
      INSERT INTO origin_coffee_types VALUES ('Ethiopia', 'POUR_OVER');
      
      INSERT INTO origins VALUES ('Colombia');
      INSERT INTO origin_coffee_types VALUES ('Colombia', 'ESPRESSO');
      INSERT INTO origin_coffee_types VALUES ('Colombia', 'POUR_OVER');
---
